project:
  type: book
  output-dir: docs

book:
  title: "livrojs"
  author: "Robin Kohrs"
  date: "7/22/2022"
  toc: true
  toc-depth: 3
  chapters:
    - index.qmd
    - looping.qmd
    - svelte.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


